ALTER TYPE "OrderStatus" RENAME VALUE 'DELIVERED' TO 'DELIVERED_TO_STUDENT';
ALTER TYPE "OrderStatus" ADD VALUE 'COMPLETED';

ALTER TYPE "CancellationReasonType" ADD VALUE 'SYSTEM_TIMEOUT';

ALTER TABLE "orders"
ADD COLUMN "readyAt" TIMESTAMP(3),
ADD COLUMN "deliveredAt" TIMESTAMP(3),
ADD COLUMN "completedAt" TIMESTAMP(3);
